package generatorrunning

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"lore-master/libs/content-generation/generatedfile"
	"lore-master/libs/markdown-workspace/syncannotation"
)

func produce(files map[string]string, warnings ...string) generatedfile.GenerateFunc {
	return func(context.Context, string, generatedfile.Spec) (generatedfile.Output, error) {
		out := generatedfile.Output{Warnings: warnings}
		for path, body := range files {
			out.Files = append(out.Files, generatedfile.File{Path: path, Body: []byte(body)})
		}

		return out, nil
	}
}

var spec = generatedfile.Spec{Type: "test-results", Output: "docs/tests"}

func read(t *testing.T, root string, relative string) string {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(relative)))
	if err != nil {
		t.Fatal(err)
	}

	return string(content)
}

func put(t *testing.T, root string, relative string, content string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestRunCreatesPagesMarkedAsGeneratedAndSortedByPath(t *testing.T) {
	root := t.TempDir()

	result, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# Results\n", "suites/a.md": "# A\n"}, "note"))
	if err != nil {
		t.Fatal(err)
	}

	if want := []string{"docs/tests/README.md", "docs/tests/suites/a.md"}; !slices.Equal(result.Written, want) {
		t.Fatalf("written %q, want %q", result.Written, want)
	}
	if !slices.Equal(result.Warnings, []string{"note"}) {
		t.Fatalf("warnings %q", result.Warnings)
	}
	content := read(t, root, "docs/tests/README.md")
	document, err := syncannotation.Read([]byte(content))
	if err != nil || document.Annotation == nil || !slices.Contains(document.Annotation.Unknown, syncannotation.Field{Key: "generated", Value: "test-results"}) {
		t.Fatalf("no marker in %q (%v)", content, err)
	}
	if string(document.Body) != "# Results\n" {
		t.Fatalf("body %q", document.Body)
	}
	if document.Annotation.PageID != "" {
		t.Fatal("a new page has no page id yet")
	}
}

func TestRunRewritesNothingWhenTheOutputIsUnchanged(t *testing.T) {
	root := t.TempDir()
	generate := produce(map[string]string{"README.md": "# Results\n"})
	if _, err := Run(context.Background(), root, spec, generate); err != nil {
		t.Fatal(err)
	}
	before := read(t, root, "docs/tests/README.md")

	result, err := Run(context.Background(), root, spec, generate)
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Written) != 0 || !slices.Equal(result.Unchanged, []string{"docs/tests/README.md"}) {
		t.Fatalf("result %+v", result)
	}
	if read(t, root, "docs/tests/README.md") != before {
		t.Fatal("the file changed")
	}
}

func TestRunKeepsTheSyncAnnotationWhenTheBodyChanges(t *testing.T) {
	root := t.TempDir()
	if _, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# Results\n\n3 passed\n"})); err != nil {
		t.Fatal(err)
	}
	full := filepath.Join(root, "docs", "tests", "README.md")
	synced := syncannotation.Annotation{
		Platform: "confluence", Space: "ENG", PageID: "42", Version: 3, ContentHash: "sha256:abc",
		Unknown: []syncannotation.Field{{Key: "generated", Value: "test-results"}},
	}
	if _, err := syncannotation.Write(full, synced); err != nil {
		t.Fatal(err)
	}

	result, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# Results\n\n2 passed, 1 failed\n"}))
	if err != nil {
		t.Fatal(err)
	}

	if !slices.Equal(result.Written, []string{"docs/tests/README.md"}) {
		t.Fatalf("result %+v", result)
	}
	document, err := syncannotation.Read([]byte(read(t, root, "docs/tests/README.md")))
	if err != nil || document.Annotation == nil {
		t.Fatalf("annotation lost: %v", err)
	}
	if document.Annotation.PageID != "42" || document.Annotation.Version != 3 || document.Annotation.ContentHash != "sha256:abc" {
		t.Fatalf("annotation changed: %+v", document.Annotation)
	}
	if string(document.Body) != "# Results\n\n2 passed, 1 failed\n" {
		t.Fatalf("body %q", document.Body)
	}
}

func TestRunNeverOverwritesAFileItDidNotGenerate(t *testing.T) {
	root := t.TempDir()
	put(t, root, "docs/tests/README.md", "# Written by hand\n")
	put(t, root, "docs/tests/other.md", "<!-- lore-master\ngenerated: go-docs\n-->\n# Another generator's page\n")

	result, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# Results\n", "other.md": "# Mine\n"}))
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Written) != 0 || len(result.Warnings) != 2 {
		t.Fatalf("result %+v", result)
	}
	for _, warning := range result.Warnings {
		if !strings.Contains(warning, "was not generated by test-results") {
			t.Fatalf("warning %q", warning)
		}
	}
	if read(t, root, "docs/tests/README.md") != "# Written by hand\n" {
		t.Fatal("a hand-written file was overwritten")
	}
}

func TestRunRemovesStaleGeneratedPagesOnly(t *testing.T) {
	root := t.TempDir()
	if _, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# R\n", "suites/old.md": "# Old\n", "suites/keep.md": "# Keep\n"})); err != nil {
		t.Fatal(err)
	}
	put(t, root, "docs/tests/notes.md", "# Hand-written notes\n")

	result, err := Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# R\n", "suites/keep.md": "# Keep\n"}))
	if err != nil {
		t.Fatal(err)
	}

	if !slices.Equal(result.Removed, []string{"docs/tests/suites/old.md"}) {
		t.Fatalf("removed %q", result.Removed)
	}
	if _, err := os.Stat(filepath.Join(root, "docs", "tests", "notes.md")); err != nil {
		t.Fatal("a hand-written page was removed")
	}

	result, err = Run(context.Background(), root, spec, produce(map[string]string{"README.md": "# R\n"}))
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(result.Removed, []string{"docs/tests/suites/keep.md"}) {
		t.Fatalf("removed %q", result.Removed)
	}
	if _, err := os.Stat(filepath.Join(root, "docs", "tests", "suites")); !os.IsNotExist(err) {
		t.Fatal("the emptied folder was kept")
	}
}

func TestRunRefusesAnOutputFolderOutsideTheWorkspace(t *testing.T) {
	for _, output := range []string{"", ".", "..", "../out", "/abs/out"} {
		_, err := Run(context.Background(), t.TempDir(), generatedfile.Spec{Type: "test-results", Output: output}, produce(nil))
		if err == nil || !strings.Contains(err.Error(), "must be a folder inside the workspace") {
			t.Fatalf("output %q: %v", output, err)
		}
	}
}

func TestRunRefusesPagePathsThatEscapeOrRepeat(t *testing.T) {
	for _, path := range []string{"", "../x.md", "/x.md", "a/../b.md", "./a.md"} {
		_, err := Run(context.Background(), t.TempDir(), spec, produce(map[string]string{path: "x"}))
		if err == nil || !strings.Contains(err.Error(), "clean relative path") {
			t.Fatalf("path %q: %v", path, err)
		}
	}

	twice := func(context.Context, string, generatedfile.Spec) (generatedfile.Output, error) {
		return generatedfile.Output{Files: []generatedfile.File{{Path: "a.md"}, {Path: "a.md"}}}, nil
	}
	if _, err := Run(context.Background(), t.TempDir(), spec, twice); err == nil || !strings.Contains(err.Error(), "twice") {
		t.Fatalf("duplicate: %v", err)
	}
}

func TestRunPassesAGeneratorFailureOn(t *testing.T) {
	failing := func(context.Context, string, generatedfile.Spec) (generatedfile.Output, error) {
		return generatedfile.Output{}, errors.New("no reports found")
	}
	_, err := Run(context.Background(), t.TempDir(), spec, failing)
	if err == nil || !strings.Contains(err.Error(), `generator "test-results": no reports found`) {
		t.Fatalf("got %v", err)
	}
}

func TestRunStopsWhenCancelled(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Run(ctx, t.TempDir(), spec, produce(map[string]string{"a.md": "# A\n"})); err == nil {
		t.Fatal("expected the cancellation")
	}
}
