package generatorrunning

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"lore-master/libs/content-generation/generatedfile"
	"lore-master/libs/markdown-workspace/syncannotation"
)

// Result is what one run did, with workspace-relative '/'-separated paths.
type Result struct {
	// Written are files created or rewritten because their content changed.
	Written []string
	// Unchanged are files whose content was already what the generator produced.
	Unchanged []string
	// Removed are generated files the generator no longer produces.
	Removed []string
	// Warnings are the generator's own notes plus files left alone because they were not
	// generated by this generator.
	Warnings []string
}

// Run executes generate for spec and brings the output folder in line with what it returned.
// A generated page keeps the annotation the sync wrote into it, so regenerating never loses
// the page's identity on the platform; only its body is replaced, which the sync then sees as
// a local change. An error is for a run that could not happen at all (a bad output folder, a
// generator that failed); a file that cannot be written is a warning.
func Run(ctx context.Context, workspaceRoot string, spec generatedfile.Spec, generate generatedfile.GenerateFunc) (Result, error) {
	outputDir, err := cleanFolder(spec.Output)
	if err != nil {
		return Result{}, fmt.Errorf("generator %q: output %w", spec.Type, err)
	}
	produced, err := generate(ctx, workspaceRoot, spec)
	if err != nil {
		return Result{}, fmt.Errorf("generator %q: %w", spec.Type, err)
	}
	files, err := orderedFiles(produced.Files)
	if err != nil {
		return Result{}, fmt.Errorf("generator %q: %w", spec.Type, err)
	}

	result := Result{Warnings: slices.Clone(produced.Warnings)}
	wanted := map[string]bool{}
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return result, err
		}
		relative := path.Join(outputDir, file.Path)
		wanted[relative] = true
		switch outcome, note := writeFile(workspaceRoot, relative, spec.Type, file.Body); outcome {
		case written:
			result.Written = append(result.Written, relative)
		case unchanged:
			result.Unchanged = append(result.Unchanged, relative)
		case skipped:
			result.Warnings = append(result.Warnings, note)
		}
	}

	removed, notes := removeStale(workspaceRoot, outputDir, spec.Type, wanted)
	result.Removed = removed
	result.Warnings = append(result.Warnings, notes...)

	return result, nil
}

// cleanFolder checks that folder is a folder inside the workspace, not the workspace itself.
func cleanFolder(folder string) (string, error) {
	clean := path.Clean(filepath.ToSlash(folder))
	if folder == "" || clean == "." || clean == ".." || strings.HasPrefix(clean, "../") || path.IsAbs(clean) || filepath.IsAbs(folder) {
		return "", fmt.Errorf("%q must be a folder inside the workspace", folder)
	}

	return clean, nil
}

// orderedFiles sorts the pages by path and refuses paths that leave the output folder or
// repeat, which would make two pages fight over one file.
func orderedFiles(files []generatedfile.File) ([]generatedfile.File, error) {
	sorted := slices.Clone(files)
	slices.SortFunc(sorted, func(a, b generatedfile.File) int { return strings.Compare(a.Path, b.Path) })
	for i, file := range sorted {
		clean := path.Clean(file.Path)
		if file.Path == "" || clean != file.Path || clean == "." || clean == ".." || strings.HasPrefix(clean, "../") || path.IsAbs(clean) {
			return nil, fmt.Errorf("page path %q must be a clean relative path inside the output folder", file.Path)
		}
		if i > 0 && sorted[i-1].Path == file.Path {
			return nil, fmt.Errorf("page path %q is produced twice", file.Path)
		}
	}

	return sorted, nil
}

type outcome int

const (
	written outcome = iota
	unchanged
	skipped
)

// writeFile creates the page, or replaces the body of an existing page this generator made.
func writeFile(workspaceRoot string, relative string, generatorType string, body []byte) (outcome, string) {
	full := filepath.Join(workspaceRoot, filepath.FromSlash(relative))
	existing, err := os.ReadFile(full)
	if os.IsNotExist(err) {
		content, renderErr := syncannotation.Render(body, marker(generatorType))
		if renderErr != nil {
			return skipped, fmt.Sprintf("%s: %v", relative, renderErr)
		}

		return write(full, relative, content)
	}
	if err != nil {
		return skipped, fmt.Sprintf("%s: %v", relative, err)
	}

	document, err := syncannotation.Read(existing)
	if err != nil || !isGeneratedBy(document.Annotation, generatorType) {
		return skipped, fmt.Sprintf("%s exists and was not generated by %s; it was left alone", relative, generatorType)
	}
	content, err := syncannotation.RenderWithBody(existing, *document.Annotation, body)
	if err != nil {
		return skipped, fmt.Sprintf("%s: %v", relative, err)
	}
	if slices.Equal(content, existing) {
		return unchanged, ""
	}

	return write(full, relative, content)
}

func write(full string, relative string, content []byte) (outcome, string) {
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return skipped, fmt.Sprintf("%s: %v", relative, err)
	}
	if err := os.WriteFile(full, content, 0o644); err != nil {
		return skipped, fmt.Sprintf("%s: %v", relative, err)
	}

	return written, ""
}

// removeStale deletes generated Markdown under the output folder that this run did not
// produce, then the folders that leaves empty.
func removeStale(workspaceRoot string, outputDir string, generatorType string, wanted map[string]bool) ([]string, []string) {
	var removed, notes []string
	root := filepath.Join(workspaceRoot, filepath.FromSlash(outputDir))
	_ = filepath.WalkDir(root, func(full string, entry fs.DirEntry, err error) error {
		if err != nil || entry.IsDir() || !strings.EqualFold(filepath.Ext(full), ".md") {
			return nil //nolint:nilerr // a folder that is not there has nothing stale in it
		}
		relative, relErr := filepath.Rel(workspaceRoot, full)
		if relErr != nil {
			return nil //nolint:nilerr // cannot happen under the workspace root
		}
		relative = filepath.ToSlash(relative)
		if wanted[relative] {
			return nil
		}
		content, readErr := os.ReadFile(full)
		if readErr != nil {
			return nil //nolint:nilerr // reported by nothing: it is not ours to remove
		}
		document, parseErr := syncannotation.Read(content)
		if parseErr != nil || !isGeneratedBy(document.Annotation, generatorType) {
			return nil
		}
		if removeErr := os.Remove(full); removeErr != nil {
			notes = append(notes, fmt.Sprintf("%s: could not be removed (%v)", relative, removeErr))

			return nil
		}
		removed = append(removed, relative)

		return nil
	})
	pruneEmptyFolders(root)
	slices.Sort(removed)

	return removed, notes
}

// pruneEmptyFolders removes folders under root (not root itself) that hold nothing.
func pruneEmptyFolders(root string) {
	var folders []string
	_ = filepath.WalkDir(root, func(full string, entry fs.DirEntry, err error) error {
		if err == nil && entry.IsDir() && full != root {
			folders = append(folders, full)
		}

		return nil
	})
	for i := len(folders) - 1; i >= 0; i-- {
		_ = os.Remove(folders[i]) // fails, harmlessly, when the folder is not empty
	}
}

// marker is the annotation a new generated page starts with: no page yet, only who made it.
func marker(generatorType string) syncannotation.Annotation {
	return syncannotation.Annotation{Generated: generatorType}
}

func isGeneratedBy(annotation *syncannotation.Annotation, generatorType string) bool {
	if annotation == nil {
		return false
	}

	return annotation.Generated == generatorType
}
