package sitepublish

import (
	"errors"
	"os"
	"path/filepath"

	"lore-master/libs/github-pages/siterender"
)

// MarkerFileName is the file WriteSite leaves at the root of a folder it owns. Its presence
// is what lets a later run replace the folder's content instead of refusing it.
const MarkerFileName = ".lore-master-site"

const markerContent = "This folder is generated by LoreMaster and is rewritten on every build.\n"

// legacyAsset is the stylesheet every site carries; a site written before the marker existed
// is recognised by it so an upgrade does not suddenly refuse its own earlier output.
const legacyAsset = "assets/lore-master.css"

// WriteSite makes dir hold exactly the generated site: it creates the folder, removes what an
// earlier run wrote there (leaving a .git directory alone) and writes the files and the
// ownership marker. A folder that has other content and no marker is refused with a
// *ForeignFolderError and left untouched, so pointing a build at the wrong folder never
// deletes somebody's work.
func WriteSite(dir string, files []siterender.SiteFile) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	var existing []string
	for _, entry := range entries {
		if entry.Name() != ".git" {
			existing = append(existing, entry.Name())
		}
	}
	if len(existing) > 0 && !ownedByLoreMaster(dir) {
		return &ForeignFolderError{Dir: dir, Entries: len(existing)}
	}

	for _, name := range existing {
		if err := os.RemoveAll(filepath.Join(dir, name)); err != nil {
			return err
		}
	}
	for _, file := range files {
		target := filepath.Join(dir, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, file.Content, 0o644); err != nil {
			return err
		}
	}

	return os.WriteFile(filepath.Join(dir, MarkerFileName), []byte(markerContent), 0o644)
}

// ownedByLoreMaster reports whether an earlier LoreMaster build wrote dir.
func ownedByLoreMaster(dir string) bool {
	for _, name := range []string{MarkerFileName, legacyAsset} {
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(name))); err == nil {
			return true
		}
	}

	return false
}

// IsForeignFolder reports whether err is a refusal to replace a folder LoreMaster did not write.
func IsForeignFolder(err error) bool {
	var foreign *ForeignFolderError

	return errors.As(err, &foreign)
}
