import * as vscode from 'vscode'
import type { EngineClient } from '../engine-process'
import { GENERATORS_RUN_METHOD, type Generator, type GeneratorRun, SETTINGS_READ_METHOD } from '../engine-protocol'
import { runGeneratorsCommand } from './run-generators.handler'

interface Scenario {
  messages:   string[]
  lines:      string[]
  shown:      number
  requests:   { method: string; params: unknown }[]
  quickPicks: ((items: { label: string }[]) => unknown)[]
}

const window = vscode.window as unknown as Record<string, unknown>
const original = { ...window }

function script (scenario: Scenario): void {
  window.showInformationMessage = (message: string) => {
    scenario.messages.push(`info: ${message}`)

    return Promise.resolve(undefined)
  }
  window.showWarningMessage = (message: string) => {
    scenario.messages.push(`warn: ${message}`)

    return Promise.resolve(undefined)
  }
  window.showErrorMessage = (message: string) => {
    scenario.messages.push(`error: ${message}`)

    return Promise.resolve(undefined)
  }
  window.showQuickPick = (items: { label: string }[]) => Promise.resolve(scenario.quickPicks.shift()?.(items))
}

function engine (scenario: Scenario, generators: Generator[], runs: GeneratorRun[], failRun?: string): EngineClient {
  return {
    request (method: string, params?: unknown) {
      scenario.requests.push({ method, params })
      if (method === SETTINGS_READ_METHOD) {
        return Promise.resolve({ exists: true, firstSync: false, settings: { version: 1, outputs: [], generators } } as never)
      }
      if (method === GENERATORS_RUN_METHOD && failRun) {
        return Promise.reject(new Error(failRun))
      }

      return Promise.resolve({ runs } as never)
    },
  } as unknown as EngineClient
}

const output = (scenario: Scenario): vscode.OutputChannel => ({
  appendLine: (line: string) => { scenario.lines.push(line) },
  show:       () => { scenario.shown++ },
}) as unknown as vscode.OutputChannel

const tests: Generator = { type: 'test-results', output: 'docs/tests' }
const api: Generator = { type: 'go-docs', output: 'docs/api' }

describe('runGeneratorsCommand', () => {
  let scenario: Scenario
  beforeEach(() => {
    scenario = { messages: [], lines: [], shown: 0, requests: [], quickPicks: [] }
    script(scenario);
    (vscode.workspace as { workspaceFolders: unknown }).workspaceFolders = [{ uri: { fsPath: '/w' }, name: 'w' }]
  })
  afterEach(() => {
    Object.assign(window, original);
    (vscode.workspace as { workspaceFolders: unknown }).workspaceFolders = undefined
  })

  const runRequests = (): unknown[] => scenario.requests.filter(request => request.method === GENERATORS_RUN_METHOD).map(request => request.params)

  it('runs the only generator without asking and reports a one-line summary', async () => {
    await runGeneratorsCommand({ engine: engine(scenario, [tests], [{ index: 0, type: 'test-results', output: 'docs/tests', written: ['a.md'], unchanged: ['b.md'] }]), output: output(scenario) })

    expect(runRequests()).toEqual([{ workspaceRoot: '/w', generators: [0] }])
    expect(scenario.messages).toEqual(['info: LoreMaster: 1 page written, 1 unchanged, 0 removed by 1 generator.'])
    expect(scenario.lines).toEqual(['test-results → docs/tests: 1 page written, 1 unchanged, 0 removed'])
    expect(scenario.shown).toBe(0)
  })

  it('asks which generators to run when there are several, and runs the chosen one', async () => {
    scenario.quickPicks.push(items => items.find(item => item.label === 'go-docs'))

    await runGeneratorsCommand({ engine: engine(scenario, [tests, api], [{ index: 1, type: 'go-docs', output: 'docs/api', written: ['x.md'] }]), output: output(scenario) })

    expect(runRequests()).toEqual([{ workspaceRoot: '/w', generators: [1] }])
  })

  it('runs them all when asked to', async () => {
    scenario.quickPicks.push(items => items.find(item => item.label === 'All generators'))

    await runGeneratorsCommand({ engine: engine(scenario, [tests, api], []), output: output(scenario) })

    expect(runRequests()).toEqual([{ workspaceRoot: '/w', generators: [0, 1] }])
  })

  it('does nothing when the choice is cancelled', async () => {
    scenario.quickPicks.push(() => undefined)

    await runGeneratorsCommand({ engine: engine(scenario, [tests, api], []), output: output(scenario) })

    expect(runRequests()).toEqual([])
    expect(scenario.messages).toEqual([])
  })

  it('warns and opens the output when a generator failed or left something alone', async () => {
    await runGeneratorsCommand({
      engine: engine(scenario, [tests], [{ index: 0, type: 'test-results', output: 'docs/tests', warnings: ['docs/tests/README.md exists and was not generated by test-results; it was left alone'] }]),
      output: output(scenario),
    })

    expect(scenario.messages[0]).toMatch(/^warn: LoreMaster: 0 pages written.* see the LoreMaster output\.$/)
    expect(scenario.lines).toContain('  ! docs/tests/README.md exists and was not generated by test-results; it was left alone')
    expect(scenario.shown).toBe(1)
  })

  it('says how to configure one when there are none', async () => {
    await runGeneratorsCommand({ engine: engine(scenario, [], []), output: output(scenario) })

    expect(scenario.messages).toHaveLength(1)
    expect(scenario.messages[0]).toContain('no generators are configured')
    expect(runRequests()).toEqual([])
  })

  it('shows the engine\'s reason when the call fails', async () => {
    await runGeneratorsCommand({ engine: engine(scenario, [tests], [], 'outputs[0].mermaidMode "x" is not valid'), output: output(scenario) })

    expect(scenario.messages).toEqual(['error: LoreMaster: outputs[0].mermaidMode "x" is not valid'])
  })

  it('asks for a folder first', async () => {
    (vscode.workspace as { workspaceFolders: unknown }).workspaceFolders = undefined

    await runGeneratorsCommand({ engine: engine(scenario, [tests], []), output: output(scenario) })

    expect(scenario.messages).toEqual(['info: LoreMaster: open a folder to run its generators.'])
  })
})
